import { type Request, type Response } from 'express';
import { prisma } from '../config/prisma.js';

/**
 * 📦 ENDPOINT 1: Add a new EV part to the shelf
 * Route: POST /api/inventory
 */
export const createInventoryItem = async (req: Request, res: Response) => {
  try {
    const shopId = (req as any).user?.shopId;
if (!shopId) return res.status(403).json({ message: 'Shop not found.' });
    const { partName, category, stockLevel, retailPrice, lowStockAlert } = req.body;

    if (!partName || !category || retailPrice === undefined || Number(retailPrice) < 0 || Number(stockLevel) < 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields. Please provide partName, category, and retailPrice.',
      });
    }

    const categoryPrefix = category.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase() || 'GEN';
    const nameInitials = partName
      .split(' ')
      .map((word: string) => word.charAt(0))
      .join('')
      .replace(/[^a-zA-Z0-9]/g, '')
      .substring(0, 3)
      .toUpperCase() || 'PRT';

    const uniqueSuffix = Math.floor(1000 + Math.random() * 9000);
    const autoGeneratedSku = `${categoryPrefix}-${nameInitials}-${uniqueSuffix}`;

    const newItem = await prisma.inventory.create({
      data: {
        partName,
        sku: autoGeneratedSku,
        category,
        stockLevel: stockLevel ? Number(stockLevel) : 0,
        retailPrice: Number(retailPrice),
        lowStockAlert: lowStockAlert ? Number(lowStockAlert) : 5,
        shopId
      },
    });

    

    return res.status(201).json({
      success: true,
      message: 'Inventory item added successfully with automated tracking code!',
      item: newItem,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error creating inventory item:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Server error occurred while executing stock allocation record.'
    });
  }
};

export const searchInventory = async (req: Request, res: Response) => {
  try {
    const shopId = (req as any).user?.shopId;
    const { q, limit = 10 } = req.query;

    if (!q || typeof q !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Query parameter "q" is required.',
      });
    }

    const items = await prisma.inventory.findMany({
      where: {
        shopId,
        OR: [
          { partName: { contains: q, mode: 'insensitive' } },
          { sku: { contains: q, mode: 'insensitive' } },
          { category: { contains: q, mode: 'insensitive' } },
        ],
      },
      take: Math.min(Number(limit), 50),
    });

    return res.status(200).json({
      success: true,
      items,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error searching inventory:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Failed to search inventory.',
    });
  }
};

/**
 * 📋 ENDPOINT: Fetch the complete inventory list
 * Route: GET /api/inventory
 */
export const getAllInventory = async (req: Request, res: Response) => {
  try {
    const shopId = (req as any).user?.shopId;
    console.log((req as any).user);
    
if (!shopId) return res.status(403).json({ message: 'Shop not found.' });
    const items = await prisma.inventory.findMany({
      where:{shopId},
      orderBy: {
        createdAt: 'desc',
      },
    });

    return res.status(200).json({
      success: true,
      items,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error fetching inventory:', errorInstance);
    return res.status(500).json({ success: false, error: 'Failed to retrieve inventory data.' });
  }
};

/**
 * ✏️ ENDPOINT: Update an inventory item
 * Route: PUT /api/inventory/:id
 */
export const updateInventoryItem = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { partName, category, stockLevel, retailPrice, lowStockAlert } = req.body;

    if (!id || isNaN(Number(id))) {
      return res.status(400).json({
        success: false,
        error: 'Invalid inventory item ID.',
      });
    }

    if (!partName && !category && stockLevel === undefined && retailPrice === undefined && lowStockAlert === undefined) {
      return res.status(400).json({
        success: false,
        error: 'At least one field must be provided to update.',
      });
    }

    const existingItem = await prisma.inventory.findUnique({
      where: { id: Number(id) },
    });

    if (!existingItem) {
      return res.status(404).json({
        success: false,
        error: 'Inventory item not found.',
      });
    }

    const updateData: Record<string, unknown> = {};
    if (partName) updateData.partName = partName;
    if (category) updateData.category = category;
    if (stockLevel !== undefined) updateData.stockLevel = Number(stockLevel);
    if (retailPrice !== undefined) updateData.retailPrice = Number(retailPrice);
    if (lowStockAlert !== undefined) updateData.lowStockAlert = Number(lowStockAlert);

    const updatedItem = await prisma.inventory.update({
      where: { id: Number(id) },
      data: updateData,
    });

    return res.status(200).json({
      success: true,
      message: 'Inventory item updated successfully.',
      item: updatedItem,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error updating inventory item:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Server error occurred while updating inventory item.',
    });
  }
};

/**
 * 🗑️ ENDPOINT: Delete an inventory item
 * Route: DELETE /api/inventory/:id
 */
export const deleteInventoryItem = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    if (!id || isNaN(Number(id))) {
      return res.status(400).json({
        success: false,
        error: 'Invalid inventory item ID.',
      });
    }

    const existingItem = await prisma.inventory.findUnique({
      where: { id: Number(id) },
    });

    if (!existingItem) {
      return res.status(404).json({
        success: false,
        error: 'Inventory item not found.',
      });
    }

    await prisma.inventory.delete({
      where: { id: Number(id) },
    });

    return res.status(200).json({
      success: true,
      message: 'Inventory item deleted successfully.',
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error deleting inventory item:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Server error occurred while deleting inventory item.',
    });
  }
};

/**
 * 📦 ENDPOINT: Add stock to an inventory item
 * Route: PATCH /api/inventory/:id/stock
 */
export const addStockToItem = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { quantity } = req.body;

    if (!id || isNaN(Number(id))) {
      return res.status(400).json({
        success: false,
        error: 'Invalid inventory item ID.',
      });
    }

    if (quantity === undefined || isNaN(Number(quantity)) || Number(quantity) < 0) {
      return res.status(400).json({
        success: false,
        error: 'Quantity must be a non-negative number.',
      });
    }

    const existingItem = await prisma.inventory.findUnique({
      where: { id: Number(id) },
    });

    if (!existingItem) {
      return res.status(404).json({
        success: false,
        error: 'Inventory item not found.',
      });
    }

    const updatedItem = await prisma.inventory.update({
      where: { id: Number(id) },
      data: {
        stockLevel: existingItem.stockLevel + Number(quantity),
      },
    });

    return res.status(200).json({
      success: true,
      message: `Added ${quantity} unit(s) to inventory.`,
      item: updatedItem,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error adding stock:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Server error occurred while adding stock.',
    });
  }
};

export const deductStockFromItems = async (req: Request, res: Response) => {
  try {
    const { items } = req.body;

    if (!Array.isArray(items) || items.length === 0) {
      return res.status(400).json({
        success: false,
        error: 'Items array is required and must not be empty.',
      });
    }

    for (const item of items) {
      const { id, quantity } = item;
      if (!id || !quantity || quantity < 0) {
        return res.status(400).json({
          success: false,
          error: 'Each item must have a valid id and quantity.',
        });
      }

      const inventoryItem = await prisma.inventory.findUnique({
        where: { id: Number(id) },
      });

      if (!inventoryItem) {
        return res.status(404).json({
          success: false,
          error: `Inventory item with id ${id} not found.`,
        });
      }

      if (inventoryItem.stockLevel < Number(quantity)) {
        return res.status(400).json({
          success: false,
          error: `Insufficient stock for ${inventoryItem.partName}. Available: ${inventoryItem.stockLevel}, Requested: ${quantity}`,
        });
      }

      await prisma.inventory.update({
        where: { id: Number(id) },
        data: {
          stockLevel: inventoryItem.stockLevel - Number(quantity),
        },
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Stock deducted successfully.',
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error deducting stock:', errorInstance);
    return res.status(500).json({
      success: false,
      error: 'Server error occurred while deducting stock.',
    });
  }
};
