import { type Request, type Response } from 'express';
import { prisma } from '../config/prisma.js'; // Ensure this points to your Prisma client setup

/**
 * 📦 ENDPOINT 1: Add a new EV part to the shelf
 * Route: POST /api/inventory
 */
export const createInventoryItem = async (req: Request, res: Response) => {
  try {
    const { partName, category, stockLevel, retailPrice, lowStockAlert } = req.body;

    // 🛡️ Validation: SKU is removed from required checks because the server builds it now!
    if (!partName || !category || retailPrice === undefined ||Number(retailPrice) >= 0||Number(stockLevel) >= 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields. Please provide partName, category, and retailPrice.',
      });
    }

    // ⚡ AUTO-GENERATE SKU ALGORITHM
    // 1. Get a clean 3-letter uppercase prefix from the category string
    const categoryPrefix = category.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase() || 'GEN';
    
    // 2. Extract initials from the part name (e.g., "Ather Brake Pads" -> "ABP")
    const nameInitials = partName
      .split(' ')
      .map((word: string) => word.charAt(0))
      .join('')
      .replace(/[^a-zA-Z0-9]/g, '')
      .substring(0, 3)
      .toUpperCase() || 'PRT';

    // 3. Generate a secure 4-digit number to guarantee uniqueness against database collisions
    const uniqueSuffix = Math.floor(1000 + Math.random() * 9000);
    
    // 4. Combine elements into a clean standard token string
    const autoGeneratedSku = `${categoryPrefix}-${nameInitials}-${uniqueSuffix}`;

    const newItem = await prisma.inventory.create({
      data: {
        partName,
        sku: autoGeneratedSku, // Injecting the server-calculated tracking token safely
        category,
        stockLevel: stockLevel ? Number(stockLevel) : 0,
        retailPrice: Number(retailPrice),
        lowStockAlert: lowStockAlert ? Number(lowStockAlert) : 5,
      },
    });

    return res.status(201).json({
      success: true,
      message: 'Inventory item added successfully with automated tracking code!',
      item: newItem,
    });
  } catch (err: unknown) {
    // ✅ STRICT COMPILER FIX: Safe type checking parsing for strict linters
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error creating inventory item:', errorInstance);
    return res.status(500).json({ 
      success: false, 
      error: 'Server error occurred while executing stock allocation record.' 
    });
  }
};

/**
 * 📋 ENDPOINT: Fetch the complete inventory list
 * Route: GET /api/inventory
 */
export const getAllInventory = async (req: Request, res: Response) => {
  try {
    const items = await prisma.inventory.findMany({
      orderBy: {
        createdAt: 'desc', // Pulls latest added parts to the top of the owner's dashboard screen
      },
    });

    return res.status(200).json({
      success: true,
      items,
    });
  } catch (err: unknown) {
    const errorInstance = err instanceof Error ? err : new Error(String(err));
    console.error('Error fetching inventory:', errorInstance);
    return res.status(500).json({ success: false, error: 'Failed to retrieve inventory data.' });
  }
};

