import { error } from 'node:console';
import {  prisma } from '../config/prisma.js'
import { type Request, type Response } from 'express'

export const createTicket = async (req: Request, res: Response): Promise<void> => {
  try {
    // 📥 1. Unpack ALL potential data inputs arriving from our single frontend payload form
    const { 
      customerId,       // Provided if selecting an existing profile
      name, phone, vehicleModel, email, address, // Provided if creating a profile inline
      issueCategory, description, technicianNotes 
    } = req.body;

    // 🛡️ 2. Absolute Mandatory Checks: Every ticket needs an issue category and description notes
    if (!issueCategory || !description) {
    res.status(400).json({ error: "Missing core ticket tracking inputs (issueCategory or description)." });
    return;
    }

    // 🔧 3. Setup our target holder variable to capture the correct unique badge string
    let finalCustomerId: string;

    if (customerId) {
      // 🔍 TRACK A: OPERATE ON EXISTING CUSTOMER PROFILE RECORD
      // Pre-flight check: Verify that the passed customer identifier actually exists in our data engine
      // Note: Using 'customer' with a small 'c' to match your schema setup perfectly!
    const existingCustomer = await prisma.customer.findUnique({
        where: { id: customerId }
    });

    if (!existingCustomer) {
        res.status(404).json({ error: "Provided customer identity tracking badge not found inside database files." });
        return;
    }

      // If safe, lock it into our holder variable
        finalCustomerId = customerId;

    } else {
      // 🆕 TRACK B: DYNAMICALLY REGISTER BRAND NEW WALK-IN USER INLINE FIRST
      // Safety gate: If no customerId is sent, the worker must have filled out the inline registration boxes
    if (!name || !phone || !vehicleModel) {
        res.status(400).json({ 
        error: "Missing new walk-in registration fields. Provide name, phone, and vehicleModel to register inline." 
        });
        return;
        }

      // Action: Write the customer profile data record row into your lowercase 'customer' table
    const newCustomer = await prisma.customer.create({
        data: {
            name,
            phone,
            vehicleModel,
            email: email || null,
            address: address || null
        }
        });

      // Capture the freshly autogenerated UUID badge generated by PostgreSQL for our new user
        finalCustomerId = newCustomer.id;
    }

    // 🏗️ 4. CREATE THE REPAIR TICKET 
    // Now that finalCustomerId is guaranteed to hold a valid, active user badge string from either path, save!
    const newTicket = await prisma.repairTicket.create({
        data: {
        issueCategory,
        description,
        technicianNotes: technicianNotes || null,
        customerId: finalCustomerId // 🔌 Plugs cleanly into our foreign key socket column slot
        }
    });

    // 📤 5. Dispatch success response envelope
    res.status(201).json({
        message: "Unified service workspace entry deployed successfully.",
        ticket: newTicket
    });

    } catch (err) {
    console.error("💥 Unified Ticket Controller Error:", err);
    res.status(500).json({ error: "Internal operational system thread failed to complete database ledger commit." });
    }
};